# draft - look at every NOTE.md file and try to perform update of it to be correctly written

include:
  - ./automations/compose.yaml # INCLUDES ./automations/*.compose.yaml
  - ./databases/compose.yaml # INCLUDES ./databases/*.compose.yaml
  - ./internals/compose.yaml # INCLUDES ./internals/*.compose.yaml
  - ./networking/compose.yaml  # INCLUDES ./networking/*.compose.yaml
  - ./runners/compose.yaml  # INCLUDES ./runners/*.compose.yaml